---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Grant permissions to logs.log
        run:
          chown -R wcreativo /app/apps/realchat
          chmod 664 /app/apps/realchat/logs.log
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm django sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm django sh -c "flake8"